defmodule Memovee.SchemaTest do
  use ExUnit.Case, async: true

  alias Memovee.TestArticle

  setup do
    {:ok, _} = Application.ensure_all_started(:ecto)
    :ok
  end

  test "autogenerated ids are UUIDv7 and strictly monotonic" do
    assert {[:id], {Ecto.UUID, :autogenerate, [[version: 7, precision: :monotonic]]}} in TestArticle.__schema__(
             :autogenerate
           )

    ids = for _ <- 1..10, do: Ecto.UUID.generate(version: 7, precision: :monotonic)

    assert Enum.all?(ids, fn id -> Ecto.UUID.version(id) == 7 end)
    assert Enum.all?(Enum.zip(ids, tl(ids)), fn {a, b} -> a < b end)
  end

  test "schemas declare uuid primary keys and foreign keys" do
    assert TestArticle.__schema__(:type, :id) == Ecto.UUID
    assert TestArticle.__schema__(:type, :parent_id) == Ecto.UUID
  end

  test "changesets cast uuid values" do
    parent_id = Ecto.UUID.generate(version: 7)

    changeset =
      TestArticle.changeset(%TestArticle{}, %{"title" => "hello", "parent_id" => parent_id})

    assert changeset.valid?
    assert Ecto.Changeset.get_field(changeset, :parent_id) == parent_id
  end
end
