# Generated by Tama Kit. Installs only the public local CA into the derived Tama image.
FROM ghcr.io/upmaru/tama:0.13.3-server
USER root
COPY tls/rootCA.pem /usr/local/share/ca-certificates/tama-kit-local.crt
RUN if command -v update-ca-certificates >/dev/null 2>&1; then update-ca-certificates; elif command -v apk >/dev/null 2>&1; then apk add --no-cache ca-certificates && update-ca-certificates; else echo 'unsupported Tama image CA trust mechanism' >&2; exit 1; fi
USER tama
