# Generated by Tama Kit. Versions are a tested local-bootstrap compatibility set.

terraform {
  required_version = ">= 1.0.0"

  required_providers {
    tama = {
      source  = "upmaru/tama"
      version = "~> 0.6.3"
    }
  }
}
