import Config

# Configure your database
config :memovee, Memovee.Repo,
  username: "postgres",
  password: "postgres",
  hostname: System.get_env("DATABASE_HOST", "localhost"),
  port: String.to_integer(System.get_env("DATABASE_PORT", "5432")),
  database: "memovee_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
local_origin = System.get_env("MEMOVEE_OAUTH_ISSUER", "https://app.localhost")
local_uri = URI.parse(local_origin)

config :memovee, MemoveeWeb.Endpoint,
  url: [scheme: local_uri.scheme, host: local_uri.host, port: local_uri.port],
  http: [ip: {0, 0, 0, 0}],
  check_origin: [local_origin],
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "mrwmaZc+ttPAW1FoY0DJZhyVsGL0EciM2Vn5/RclSrhr1EaXEZtxmHnwwav0PB4z",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:memovee, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:memovee, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :memovee, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :open_api_spex, :cache_adapter, OpenApiSpex.Plug.NoneCache

config :memovee, Memovee.OAuth, allow_local_client_metadata: true

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
